; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
lib_deps = adafruit/Adafruit NeoPixel
; 串口监视器
monitor_speed = 115200

; ===== 适配 ESP32-S3 N16R8 =====
; 16MB Flash
board_upload.flash_size = 16MB

; 启用 8MB PSRAM
board_build.psram = enabled

; Flash 模式
board_build.flash_mode = qio

; 使用 16MB 分区表
board_build.partitions = default_16MB.csv

; 编译标志（让 Arduino 识别 PSRAM）
build_flags =
    -DBOARD_HAS_PSRAM 
    

    